import Head from "next/head";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Landing Page</title>
      </Head>
      <body>{children}</body>
    </html>
  );
}
